### ISSUE TITLE
when Login page loads, there is a delay while translations load?

### ISSUE THREAD

**Issue by StephenOTT** [DigitalState/SharedFront#4]
![screen shot 2017-09-07 at 7 45 42 pm](https://user-images.githubusercontent.com/1994838/30190053-a7b012f4-9405-11e7-8591-431ba55fc652.png)

There should be a loading animation/overlay/something that indicates the UI is still loading. Can the CMS translations load as part of the spinner?

Also if CMS translations are unreachable, the page will remain like the image above and does not show an error.  It should show en error

**Comment by baddlan** [comment]
Done!
